apiVersion: log.my.domain/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: cluster-logger
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  version: "v1"
  name: "testClusterScan"
  nodes:
  - name: "masterNode"
    uid: 123
    numberOfPods: 3
    master: True
    status: Active
  - name: "regularNode"
    uid: 321
    numberOfPods: 2
    master: False
    status: Active
